#pragma once

#define REQ_UNKNOWN 00

#define REQ_LOGIN 10
#define REQ_REGISTER 11
#define REQ_LOGOUT 12
#define REQ_GET_LIST_FRIEND 20
#define REQ_SEND_FRIEND_INVITATION 30
#define REQ_SEND_CHALLENGE_INVITATION 40
#define REQ_START_GAME 50
#define REQ_STOP_GAME 51
#define REQ_PLAY_CHESS 52
#define REQ_END_GAME 58
#define REQ_PENDING_START_GAME 59
#define REQ_CHAT 80

#define RESPONSE_TO_CLIENT 90

#define RESPONSE_TO_SERVER 99


#define RES_UNDENTIFIED 000

#define	RES_LOGIN_SUCCESSFUL  100
#define	RES_LOGIN_FAIL  101

#define	RES_REGISTER_SUCCESSFUL  110
#define	RES_REGISTER_FAIL  111

#define	RES_LOGOUT_SUCCESSFUL  120
#define	RES_LOGOUT_FAIL  121

#define	RES_GET_LIST_FRIEND_SUCCESSFUL 200
#define	RES_GET_LIST_FRIEND_FAIL 201

#define	RES_SEND_FRIEND_INVITATION_SUCCESSFUL 300
#define	RES_SEND_FRIEND_INVITATION_FAIL 301
#define	RES_ACCEPT_FRIEND_INVITATION 302
#define	RES_DENY_FRIEND_INVITATION 303

#define	RES_SEND_CHALLENGE_INVITATION_SUCCESSFUL 400
#define	RES_SEND_CHALLENGE_INVITATION_FAIL 401
#define	RES_ACCEPT_CHALLENGE_INVITATION 402
#define	RES_DENY_CHALLENGE_INVITATION 403

#define	RES_STOP_GAME_SUCCESSFUL 510

#define	RES_PLAY_SUCCESSFUL 520
#define	RES_PLAY_FAIL 521


#define	S2C_CHAT_SUCCESSFUL 800
#define	S2C_CHAT_FAIL 801
