#pragma once

#define REQ_UNKNOWN 00

#define C2S_LOGIN 10
#define C2S_REGISTER 11
#define C2S_LOGOUT 12
#define C2S_GET_LIST_FRIEND 20
#define C2S_SEND_FRIEND_INVITATION 30
#define C2S_SEND_CHALLENGE_INVITATION 40
#define C2S_STOP_GAME 51
#define C2S_PLAY 52
#define C2S_CHAT 80

#define RESPONSE_TO_CLIENT 90

#define S2C_SEND_LIST_FRIEND 29
#define S2C_SEND_FRIEND_INVITATION 39
#define S2C_SEND_CHALLENGE_INVITATION 49
#define S2C_START_GAME 59
#define S2C_END_GAME 58
#define S2C_SEND_LOG 69
#define S2C_SEND_CHAT 89

#define RESPONSE_TO_SERVER 99


#define UNDENTIFIED 000

#define	S2C_LOGIN_SUCCESSFUL  100
#define	S2C_LOGIN_FAIL  101
#define	S2C_LOGIN_FAIL_LOCKED  102
#define	S2C_LOGIN_FAIL_WRONG  103
#define	S2C_LOGIN_FAIL_ANOTHER_DEVICE  104
#define	S2C_LOGIN_FAIL_LOGGED  105
#define	S2C_REGISTER_SUCCESSFUL  110
#define	S2C_REGISTER_FAIL  111
#define	S2C_LOGOUT_SUCCESSFUL  120
#define	S2C_LOGOUT_FAIL  121
#define	S2C_GET_LIST_FRIEND_SUCCESSFUL 200
#define	S2C_GET_LIST_FRIEND_FAIL 201
#define	S2C_SEND_FRIEND_INVITATION_SUCCESSFUL 300
#define	S2C_SEND_FRIEND_INVITATION_FAIL 301
#define	S2C_SEND_CHALLENGE_INVITATION_SUCCESSFUL 400
#define	S2C_SEND_CHALLENGE_INVITATION_FAIL 401
#define	S2C_STOP_GAME_SUCCESS 510
#define	S2C_PLAY_SUCCESSFUL 520
#define	S2C_PLAY_FAIL 521
#define	S2C_CHAT_SUCCESSFUL 800
#define	S2C_CHAT_FAIL 801



#define	C2S_ACCEPT_FRIEND_INVITATION 390
#define	C2S_DENY_FRIEND_INVITATION 391
#define	C2S_ACCEPT_CHALLENGE_INVITATION 490
#define	C2S_DENY_CHALLENGE_INVITATION 491
#define	C2S_RECEIVED_REQUEST_START_GAME 590
#define	C2S_RECEIVED_REQUEST_END_GAME 580